#!/usr/bin/env python3
"""p116 — topologically ordered insmod script generator for vendor dlkm.

Reads modules.dep (+ modules.softdep pre-entries) from the local patched
module dir and emits a flat device shell script that insmods everything in
dependency-safe order. EEXIST (already loaded) is treated as success.
"""
import os, sys, re

D = sys.argv[1] if len(sys.argv) > 1 else "."

hard = {}      # module -> set(hard dep modules)
name_of = {}   # "audio_apr" -> "audio_apr.ko"

def norm(tok):
    tok = tok.strip()
    if tok.endswith(".ko"):
        base = tok
    else:
        base = tok + ".ko"
    return os.path.basename(base)

for line in open(os.path.join(D, "modules.dep"), encoding="utf-8", errors="replace"):
    line = line.strip()
    if not line or line.startswith("#"):
        continue
    if ":" not in line:
        hard[norm(line)] = set()
        continue
    mod, deps = line.split(":", 1)
    hard[norm(mod)] = {norm(d) for d in deps.split() if d.strip()}

pre = {}
try:
    for line in open(os.path.join(D, "modules.softdep"), encoding="utf-8", errors="replace"):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        m = re.match(r"^(\S+)\s+(.*)$", line)
        if not m:
            continue
        mod = norm(m.group(1))
        toks = m.group(2).split()
        pres, posts, cur = [], [], None
        for t in toks:
            if t == "pre:":
                cur = pres
            elif t == "post:":
                cur = posts
            elif t.startswith(":"):
                cur = posts if t == "post:" else cur
            elif cur is pres:
                pres.append(norm(t))
        pre[mod] = pres
except FileNotFoundError:
    pass

order, state = [], {}

def visit(mod, stack=()):
    mod = norm(mod)
    if mod not in hard:
        return
    if state.get(mod) == 2:
        return
    if state.get(mod) == 1:
        print(f"WARN cycle at {mod} stack={stack}", file=sys.stderr)
        return
    state[mod] = 1
    for d in sorted(pre.get(mod, [])) + sorted(hard[mod]):
        visit(d, stack + (mod,))
    state[mod] = 2
    order.append(mod)

for m in sorted(hard):
    visit(m)

with open(os.path.join(D, "load_ordered.sh"), "w", newline="\n") as f:
    f.write("#!/system/bin/sh\n")
    f.write("# generated by p116-gen-load-order.py — dependency-safe load order\n")
    f.write("DIR=/data/local/tmp/dlkm\n")
    f.write("LOG=$DIR/load_ordered.log\n: > $LOG\n")
    for x in order:
        f.write(f'insmod $DIR/{x} 2>>$LOG || echo "FAIL {x}" >> $LOG\n')
    f.write('echo "loaded=$(wc -l < /proc/modules)" >> $LOG; cat $LOG\n')
print(f"generated load_ordered.sh with {len(order)} modules")
