ccflags-y += -I$(srctree)/drivers  # p258: <../drivers/net/...> -> in-tree rmnet
obj-$(CONFIG_RMNET_PERF) += rmnet_perf.o
rmnet_perf-y := rmnet_perf_config.o rmnet_perf_core.o rmnet_perf_opt.o \
		rmnet_perf_tcp_opt.o rmnet_perf_udp_opt.o
