#!/system/bin/sh
# generated by p116-gen-load-order.py — dependency-safe load order
DIR=/data/adb/tb371fc-dlkm/dlkm
LOG=$DIR/load_ordered.log
: > $LOG
$DIR/insmod128 $DIR/q6_pdr_dlkm.ko 2>>$LOG || echo "FAIL q6_pdr_dlkm.ko" >> $LOG
$DIR/insmod128 $DIR/q6_notifier_dlkm.ko 2>>$LOG || echo "FAIL q6_notifier_dlkm.ko" >> $LOG
$DIR/insmod128 $DIR/snd_event_dlkm.ko 2>>$LOG || echo "FAIL snd_event_dlkm.ko" >> $LOG
$DIR/insmod128 $DIR/apr_dlkm.ko 2>>$LOG || echo "FAIL apr_dlkm.ko" >> $LOG
$DIR/insmod128 $DIR/adsp_loader_dlkm.ko 2>>$LOG || echo "FAIL adsp_loader_dlkm.ko" >> $LOG
$DIR/insmod128 $DIR/q6_dlkm.ko 2>>$LOG || echo "FAIL q6_dlkm.ko" >> $LOG
$DIR/insmod128 $DIR/bolero_cdc_dlkm.ko 2>>$LOG || echo "FAIL bolero_cdc_dlkm.ko" >> $LOG
$DIR/insmod128 $DIR/mbhc_dlkm.ko 2>>$LOG || echo "FAIL mbhc_dlkm.ko" >> $LOG
$DIR/insmod128 $DIR/swr_dlkm.ko 2>>$LOG || echo "FAIL swr_dlkm.ko" >> $LOG
$DIR/insmod128 $DIR/swr_ctrl_dlkm.ko 2>>$LOG || echo "FAIL swr_ctrl_dlkm.ko" >> $LOG
$DIR/insmod128 $DIR/wcd9xxx_dlkm.ko 2>>$LOG || echo "FAIL wcd9xxx_dlkm.ko" >> $LOG
$DIR/insmod128 $DIR/wcd_core_dlkm.ko 2>>$LOG || echo "FAIL wcd_core_dlkm.ko" >> $LOG
$DIR/insmod128 $DIR/wcd938x_dlkm.ko 2>>$LOG || echo "FAIL wcd938x_dlkm.ko" >> $LOG
$DIR/insmod128 $DIR/wsa881x_dlkm.ko 2>>$LOG || echo "FAIL wsa881x_dlkm.ko" >> $LOG
$DIR/insmod128 $DIR/wsa_macro_dlkm.ko 2>>$LOG || echo "FAIL wsa_macro_dlkm.ko" >> $LOG
$DIR/insmod128 $DIR/audio_machine_kona.ko 2>>$LOG || echo "FAIL audio_machine_kona.ko" >> $LOG
$DIR/insmod128 $DIR/hq_shim.ko 2>>$LOG || echo "FAIL hq_shim.ko" >> $LOG
$DIR/insmod128 $DIR/audio_tfa98xx.ko 2>>$LOG || echo "FAIL audio_tfa98xx.ko" >> $LOG
$DIR/insmod128 $DIR/gspca_main.ko 2>>$LOG || echo "FAIL gspca_main.ko" >> $LOG
$DIR/insmod128 $DIR/hdmi_dlkm.ko 2>>$LOG || echo "FAIL hdmi_dlkm.ko" >> $LOG
$DIR/insmod128 $DIR/lcd.ko 2>>$LOG || echo "FAIL lcd.ko" >> $LOG
$DIR/insmod128 $DIR/llcc_perfmon.ko 2>>$LOG || echo "FAIL llcc_perfmon.ko" >> $LOG
$DIR/insmod128 $DIR/msm_11ad_proxy.ko 2>>$LOG || echo "FAIL msm_11ad_proxy.ko" >> $LOG
$DIR/insmod128 $DIR/platform_dlkm.ko 2>>$LOG || echo "FAIL platform_dlkm.ko" >> $LOG
$DIR/insmod128 $DIR/native_dlkm.ko 2>>$LOG || echo "FAIL native_dlkm.ko" >> $LOG
$DIR/insmod128 $DIR/pinctrl_lpi_dlkm.ko 2>>$LOG || echo "FAIL pinctrl_lpi_dlkm.ko" >> $LOG
$DIR/insmod128 $DIR/pinctrl_wcd_dlkm.ko 2>>$LOG || echo "FAIL pinctrl_wcd_dlkm.ko" >> $LOG
$DIR/insmod128 $DIR/qca_cld3_qca6390.ko 2>>$LOG || echo "FAIL qca_cld3_qca6390.ko" >> $LOG
$DIR/insmod128 $DIR/qca_cld3_qca6490.ko 2>>$LOG || echo "FAIL qca_cld3_qca6490.ko" >> $LOG
$DIR/insmod128 $DIR/rdbg.ko 2>>$LOG || echo "FAIL rdbg.ko" >> $LOG
$DIR/insmod128 $DIR/rmnet_perf.ko 2>>$LOG || echo "FAIL rmnet_perf.ko" >> $LOG
$DIR/insmod128 $DIR/rmnet_shs.ko 2>>$LOG || echo "FAIL rmnet_shs.ko" >> $LOG
$DIR/insmod128 $DIR/rx_macro_dlkm.ko 2>>$LOG || echo "FAIL rx_macro_dlkm.ko" >> $LOG
$DIR/insmod128 $DIR/stub_dlkm.ko 2>>$LOG || echo "FAIL stub_dlkm.ko" >> $LOG
$DIR/insmod128 $DIR/tx_macro_dlkm.ko 2>>$LOG || echo "FAIL tx_macro_dlkm.ko" >> $LOG
$DIR/insmod128 $DIR/usf_dlkm.ko 2>>$LOG || echo "FAIL usf_dlkm.ko" >> $LOG
$DIR/insmod128 $DIR/va_macro_dlkm.ko 2>>$LOG || echo "FAIL va_macro_dlkm.ko" >> $LOG
$DIR/insmod128 $DIR/wcd938x_slave_dlkm.ko 2>>$LOG || echo "FAIL wcd938x_slave_dlkm.ko" >> $LOG
$DIR/insmod128 $DIR/wil6210.ko 2>>$LOG || echo "FAIL wil6210.ko" >> $LOG
echo "loaded=$(wc -l < /proc/modules)" >> $LOG; cat $LOG
