# SPDX-License-Identifier: GPL-2.0
obj-	+= incrementalfs.o

incrementalfs-y := \
	data_mgmt.o \
	format.o \
	integrity.o \
	main.o \
	pseudo_files.o \
	sysfs.o \
	vfs.o

# incrementalfs- += verity.o  # disabled: verity.c corrupted