name: Update 鍚堝苟 branch
on:
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 4.19.315
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 1

      - name: Update 鍚堝苟 branch
        run: |
          git fetch origin merge-android-upstream
          git push origin merge-android-upstream:鍚堝苟 --force
